{"uuid": "77692dbb-c952-4159-81df-06772f7ba9b9", "children": ["362dc603-4eed-4156-abd2-291aa2fc9ab2"], "befores": [{"name": "beforeClass", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: chrome not reachable\n  (Session info: chrome=103.0.5060.134)\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x01135FD3+2187219]\n\tOrdinal0 [0x010CE6D1+1763025]\n\tOrdinal0 [0x00FE3D40+802112]\n\tOrdinal0 [0x00FD8A12+756242]\n\tOrdinal0 [0x00FD9248+758344]\n\tOrdinal0 [0x00FDAB02+764674]\n\tOrdinal0 [0x00FD4379+738169]\n\tOrdinal0 [0x00FE51D0+807376]\n\tOrdinal0 [0x0103C7A2+1165218]\n\tOrdinal0 [0x0102C9A6+1100198]\n\tOrdinal0 [0x01006F80+946048]\n\tOrdinal0 [0x01007E76+949878]\n\tGetHandleVerifier [0x013D90C2+2721218]\n\tGetHandleVerifier [0x013CAAF0+2662384]\n\tGetHandleVerifier [0x011C137A+526458]\n\tGetHandleVerifier [0x011C0416+522518]\n\tOrdinal0 [0x010D4EAB+1789611]\n\tOrdinal0 [0x010D97A8+1808296]\n\tOrdinal0 [0x010D9895+1808533]\n\tOrdinal0 [0x010E26C1+1844929]\n\tBaseThreadInitThunk [0x761DFA29+25]\n\tRtlGetAppContainerNamedObjectPath [0x77BB7A7E+286]\n\tRtlGetAppContainerNamedObjectPath [0x77BB7A4E+238]\n\n", "trace": "  File \"C:\\Users\\ajinkyas.shukla_info\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\ajinkyas.shukla_info\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\ajinkyas.shukla_info\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 883, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\PracticeFramework\\SeleniumPracticeFramework\\test\\conftest.py\", line 15, in beforeClass\n    driver.maximize_window()\n  File \"C:\\Users\\ajinkyas.shukla_info\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 990, in maximize_window\n    self.execute(command, params)\n  File \"C:\\Users\\ajinkyas.shukla_info\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 430, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\ajinkyas.shukla_info\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1658753123748, "stop": 1658753136828}], "start": 1658753123748, "stop": 1658753136893}